#!/usr/bin/env bash

set -e

# Determine the script path
TARGET_FILE=$0
cd "$(dirname "$TARGET_FILE")"
TARGET_FILE=$(basename "$TARGET_FILE")
# Iterate down a (possible) chain of symlinks
while [ -L "$TARGET_FILE" ]; do
  TARGET_FILE=$(readlink "$TARGET_FILE")
  cd "$(dirname "$TARGET_FILE")"
  TARGET_FILE=$(basename "$TARGET_FILE")
done
# Put it all together
SCRIPT_PATH=$(pwd -P)/$TARGET_FILE
ROOT=$(dirname $SCRIPT_PATH)

###
# Installer
###

# Homebrew
ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
# Install everything from Brewfile
brew bundle $ROOT/Brewfile
# Install Casks
$ROOT/home/.cask

# OSX defaults
$ROOT/home/.osx

# Ruby
RUBY_VERSION="2.0.0-p353"
rbenv install $RUBY_VERSION
rbenv global $RUBY_VERSION
rbenv rehash

# Gems
bundle install --gemfile=$ROOT/Gemfile
rbenv rehash

# Oh-my-zsh
curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Homesick
homesick clone cknadler/dotfiles
homesick symlink dotfiles

# Fonts
mkdir -p $HOME/Library/Fonts
cp $ROOT/fonts/* $HOME/Library/Fonts

# iTerm 2 colors
open $ROOT/colors/Tomorrow\ Night\ Bright.itermcolors

# vim-anywhere
# Should always be installed last as it will focus the screen
curl -fsSL https://raw.github.com/cknadler/vim-anywhere/master/install | bash
