#!/usr/bin/env bash

set -e

###
# TODO
# - Run this assuming no git at first
###

###
# functions
###

installed() { hash $1 &> /dev/null; }

###
# globals
###

# Determine the script path
TARGET_FILE=$0
cd "$(dirname "$TARGET_FILE")"
TARGET_FILE=$(basename "$TARGET_FILE")
# Iterate down a (possible) chain of symlinks
while [ -L "$TARGET_FILE" ]; do
  TARGET_FILE=$(readlink "$TARGET_FILE")
  cd "$(dirname "$TARGET_FILE")"
  TARGET_FILE=$(basename "$TARGET_FILE")
done
# Put it all together
SCRIPT_PATH=$(pwd -P)/$TARGET_FILE
ROOT=$(dirname $SCRIPT_PATH)

###
# installer
###

# command line tools
# note: must come before brew bundle
if ! xcode-select -p 1>/dev/null; then
  xcode-select --install
fi

# Homebrew
if ! installed brew; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# install brewdler
brew tap Homebrew/bundle
# install everything from Brewfile
brew bundle

# install lastest ruby version
rbenv install $(rbenv install -l | grep -v - | tail -1)

# gems
sudo gem install bundler
bundle install --gemfile=$ROOT/Gemfile

# oh-my-zsh
if ! [[ -d $HOME/.oh-my-zsh ]]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# homesick
homesick clone cknadler/dotfiles
homesick symlink dotfiles

# submodules
pushd ~/.homesick/repos/dotfiles
git submodule sync
popd

# fonts
mkdir -p $HOME/Library/Fonts
cp $ROOT/fonts/* $HOME/Library/Fonts

# vim-anywhere
if ! [[ -d $HOME/.vim-anywhere ]]; then
  curl -fsSL https://raw.github.com/cknadler/vim-anywhere/master/install | bash
fi

# OSX defaults
# should always be run last as it will shut down Terminal
$ROOT/home/.osx
