#!/usr/bin/env ruby

ws = "/Users/kndlrc/workspace"
exit unless File.exists?(ws)

Dir.foreach(ws) do |f|
  next if f.match(/\..*/)
  als = f.gsub(/[a-z]/, "").downcase
  puts "alias #{als}='cd #{ws}/#{f}';"
end
